{
  "formatVersion": "1.1",
  "component": {
    "group": "net.notjustanna.webview",
    "module": "webview_java-native-linux-x86-64",
    "version": "1.5.0+wv0.12.0-nightly.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "webview_java-native-linux-x86-64-1.5.0+wv0.12.0-nightly.1.jar",
          "url": "webview_java-native-linux-x86-64-1.5.0+wv0.12.0-nightly.1.jar",
          "size": 40776,
          "sha512": "02e07bb5e4a72920a465f7f6ca445ea1eb07b578bdc17a31714a27d0059d75fccd17824d1485ec7a198b80b73b652a6df3647bc2109203c44b2b291cc961bd9d",
          "sha256": "e86315ccb39e106213c5e501b8ba540318d0de72a41ba4ae9dd14c6ff0526ae2",
          "sha1": "920b5c3abcca32a9c61f1819d3334970f990c38d",
          "md5": "57ccbee7501e75235662aecb7e348bb9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webview_java-native-linux-x86-64-1.5.0+wv0.12.0-nightly.1.jar",
          "url": "webview_java-native-linux-x86-64-1.5.0+wv0.12.0-nightly.1.jar",
          "size": 40776,
          "sha512": "02e07bb5e4a72920a465f7f6ca445ea1eb07b578bdc17a31714a27d0059d75fccd17824d1485ec7a198b80b73b652a6df3647bc2109203c44b2b291cc961bd9d",
          "sha256": "e86315ccb39e106213c5e501b8ba540318d0de72a41ba4ae9dd14c6ff0526ae2",
          "sha1": "920b5c3abcca32a9c61f1819d3334970f990c38d",
          "md5": "57ccbee7501e75235662aecb7e348bb9"
        }
      ]
    }
  ]
}
