{
  "formatVersion": "1.1",
  "component": {
    "group": "net.notjustanna.webview",
    "module": "webview_java-native-darwin",
    "version": "1.0.0+wv0.12.0-nightly.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "webview_java-native-darwin-1.0.0+wv0.12.0-nightly.1.jar",
          "url": "webview_java-native-darwin-1.0.0+wv0.12.0-nightly.1.jar",
          "size": 76796,
          "sha512": "582a50ecb87686423f36c01b57f1e45413f5f1094d317d1b2bcefa5d29e3c167cddfd8c53938077ae76bf2b4d92848c8f559f29c7feec63f294920d32e3444fc",
          "sha256": "7047c6dffecb47b720b1b24fd5fa129ffb63e8625e2d9d5f01e731622f9160df",
          "sha1": "df107f3834f8031cfcb8156e2e405ba426ad3e44",
          "md5": "386e16951a47807ef7f37c52a51a94cc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webview_java-native-darwin-1.0.0+wv0.12.0-nightly.1.jar",
          "url": "webview_java-native-darwin-1.0.0+wv0.12.0-nightly.1.jar",
          "size": 76796,
          "sha512": "582a50ecb87686423f36c01b57f1e45413f5f1094d317d1b2bcefa5d29e3c167cddfd8c53938077ae76bf2b4d92848c8f559f29c7feec63f294920d32e3444fc",
          "sha256": "7047c6dffecb47b720b1b24fd5fa129ffb63e8625e2d9d5f01e731622f9160df",
          "sha1": "df107f3834f8031cfcb8156e2e405ba426ad3e44",
          "md5": "386e16951a47807ef7f37c52a51a94cc"
        }
      ]
    }
  ]
}
