{
  "formatVersion": "1.1",
  "component": {
    "group": "net.notjustanna.webview",
    "module": "webview_java-all-natives",
    "version": "1.4.0+wv0.12.0-nightly.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "webview_java-all-natives-1.4.0+wv0.12.0-nightly.1.jar",
          "url": "webview_java-all-natives-1.4.0+wv0.12.0-nightly.1.jar",
          "size": 261,
          "sha512": "e4e73e90008f04d13b06230aa598b002e3b7b49b3e7e1a227f8ed60dfc76b7f5d015aaa403bd386a340de634c413c36fc65958c26de13a2dd96465f936569ddb",
          "sha256": "a6a5a46bbc186ed066020082c958afde28689fdf1f723560b13d4bb1b024f3d6",
          "sha1": "1b7562de983fbec2c9034dc007883790ce217951",
          "md5": "a638cecb317341b55aec43f281fd4a65"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.notjustanna.webview",
          "module": "webview_java-native-darwin",
          "version": {
            "requires": "1.4.0+wv0.12.0-nightly.1"
          }
        },
        {
          "group": "net.notjustanna.webview",
          "module": "webview_java-native-linux-x86-64",
          "version": {
            "requires": "1.4.0+wv0.12.0-nightly.1"
          }
        },
        {
          "group": "net.notjustanna.webview",
          "module": "webview_java-native-windows-arm64",
          "version": {
            "requires": "1.4.0+wv0.12.0-nightly.1"
          }
        },
        {
          "group": "net.notjustanna.webview",
          "module": "webview_java-native-windows-x86",
          "version": {
            "requires": "1.4.0+wv0.12.0-nightly.1"
          }
        },
        {
          "group": "net.notjustanna.webview",
          "module": "webview_java-native-windows-x86-64",
          "version": {
            "requires": "1.4.0+wv0.12.0-nightly.1"
          }
        }
      ],
      "files": [
        {
          "name": "webview_java-all-natives-1.4.0+wv0.12.0-nightly.1.jar",
          "url": "webview_java-all-natives-1.4.0+wv0.12.0-nightly.1.jar",
          "size": 261,
          "sha512": "e4e73e90008f04d13b06230aa598b002e3b7b49b3e7e1a227f8ed60dfc76b7f5d015aaa403bd386a340de634c413c36fc65958c26de13a2dd96465f936569ddb",
          "sha256": "a6a5a46bbc186ed066020082c958afde28689fdf1f723560b13d4bb1b024f3d6",
          "sha1": "1b7562de983fbec2c9034dc007883790ce217951",
          "md5": "a638cecb317341b55aec43f281fd4a65"
        }
      ]
    }
  ]
}
