{
  "formatVersion": "1.1",
  "component": {
    "group": "net.notjustanna.webview",
    "module": "webview_java-native-linux-x86-64",
    "version": "1.0.0+wv0.12.0-nightly.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "webview_java-native-linux-x86-64-1.0.0+wv0.12.0-nightly.1.jar",
          "url": "webview_java-native-linux-x86-64-1.0.0+wv0.12.0-nightly.1.jar",
          "size": 40776,
          "sha512": "a3e379cbf7a64cb43d8c8169c7928ec45fc9d68fe837ec4e79ebe709c54d51fe0f33324d5efe5560b2706e3714b73063152bea51b00a3bfbed0fe38e8d595680",
          "sha256": "0d1f07af819d0c12377c29015a8e77a9559bcf6a89d9bfbeaa5e27bd6b4fc42c",
          "sha1": "a1df7c6decf546c27293829e76312fbdc774fa8f",
          "md5": "cc58df214162853270f6c9320eb13af1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webview_java-native-linux-x86-64-1.0.0+wv0.12.0-nightly.1.jar",
          "url": "webview_java-native-linux-x86-64-1.0.0+wv0.12.0-nightly.1.jar",
          "size": 40776,
          "sha512": "a3e379cbf7a64cb43d8c8169c7928ec45fc9d68fe837ec4e79ebe709c54d51fe0f33324d5efe5560b2706e3714b73063152bea51b00a3bfbed0fe38e8d595680",
          "sha256": "0d1f07af819d0c12377c29015a8e77a9559bcf6a89d9bfbeaa5e27bd6b4fc42c",
          "sha1": "a1df7c6decf546c27293829e76312fbdc774fa8f",
          "md5": "cc58df214162853270f6c9320eb13af1"
        }
      ]
    }
  ]
}
