{
  "formatVersion": "1.1",
  "component": {
    "group": "net.notjustanna.webview",
    "module": "webview_java-native-windows-x86-64",
    "version": "1.3.0+wv0.12.0-nightly.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "webview_java-native-windows-x86-64-1.3.0+wv0.12.0-nightly.1.jar",
          "url": "webview_java-native-windows-x86-64-1.3.0+wv0.12.0-nightly.1.jar",
          "size": 46811,
          "sha512": "55f29b352e46a11956cc7127bde4ddc714170c216f3ebdf7fbb59bc98f1066ebd2543d296228652080f511a27cd2bfb2331d9b6e834dfc599f256506ec51c5fd",
          "sha256": "6ad8773e479cb9191c1b97c550111fd2380973e9f3d18a5db356234cd90ba97b",
          "sha1": "e097262008af8fff2180daebe979dda7c0709e57",
          "md5": "b26b9ad10aea627b942719460bbe12ed"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webview_java-native-windows-x86-64-1.3.0+wv0.12.0-nightly.1.jar",
          "url": "webview_java-native-windows-x86-64-1.3.0+wv0.12.0-nightly.1.jar",
          "size": 46811,
          "sha512": "55f29b352e46a11956cc7127bde4ddc714170c216f3ebdf7fbb59bc98f1066ebd2543d296228652080f511a27cd2bfb2331d9b6e834dfc599f256506ec51c5fd",
          "sha256": "6ad8773e479cb9191c1b97c550111fd2380973e9f3d18a5db356234cd90ba97b",
          "sha1": "e097262008af8fff2180daebe979dda7c0709e57",
          "md5": "b26b9ad10aea627b942719460bbe12ed"
        }
      ]
    }
  ]
}
