{
  "formatVersion": "1.1",
  "component": {
    "group": "net.notjustanna.webview",
    "module": "webview_java-native-windows-x86-64",
    "version": "1.3.0+wv0.12.0-nightly.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "webview_java-native-windows-x86-64-1.3.0+wv0.12.0-nightly.1.jar",
          "url": "webview_java-native-windows-x86-64-1.3.0+wv0.12.0-nightly.1.jar",
          "size": 46811,
          "sha512": "2e6bd18f9e84260ca07f862dfc34f4a5f5634e1be3ec00b15fca2ee115a2c1e19626805dbcfbf4853168c75fb4e79e260e05557a882e2e01c80f5481be866272",
          "sha256": "8384b0ae5425e4dbc8fa6e70a36932df468105ef19b8d7e62bd24b838a841672",
          "sha1": "bbcc940380b82f133da83bffd700db85e4418045",
          "md5": "4150e424dc8e7c6fd5a02197260463cd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webview_java-native-windows-x86-64-1.3.0+wv0.12.0-nightly.1.jar",
          "url": "webview_java-native-windows-x86-64-1.3.0+wv0.12.0-nightly.1.jar",
          "size": 46811,
          "sha512": "2e6bd18f9e84260ca07f862dfc34f4a5f5634e1be3ec00b15fca2ee115a2c1e19626805dbcfbf4853168c75fb4e79e260e05557a882e2e01c80f5481be866272",
          "sha256": "8384b0ae5425e4dbc8fa6e70a36932df468105ef19b8d7e62bd24b838a841672",
          "sha1": "bbcc940380b82f133da83bffd700db85e4418045",
          "md5": "4150e424dc8e7c6fd5a02197260463cd"
        }
      ]
    }
  ]
}
