{
  "formatVersion": "1.1",
  "component": {
    "group": "net.notjustanna.webview",
    "module": "webview_java-native-windows-arm64",
    "version": "1.0.0+wv0.12.0-nightly.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "webview_java-native-windows-arm64-1.0.0+wv0.12.0-nightly.1.jar",
          "url": "webview_java-native-windows-arm64-1.0.0+wv0.12.0-nightly.1.jar",
          "size": 43048,
          "sha512": "05a3e38c43bc406c75c51b343719d66b05cd44447a932f27dc108a8f78696f4ba6a51d39d729bfab2deef8b3c60d95c85271df681691999b12e8377dd0554f3b",
          "sha256": "ea0cbdbdad56c49cef0e2f8fe95914ecc0f2b43decfff20630ef3001a53a1209",
          "sha1": "6660876b6423b19d649d14cc20841c43cfbac5f6",
          "md5": "b55f01fb05370e421ad7c2b989aee770"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webview_java-native-windows-arm64-1.0.0+wv0.12.0-nightly.1.jar",
          "url": "webview_java-native-windows-arm64-1.0.0+wv0.12.0-nightly.1.jar",
          "size": 43048,
          "sha512": "05a3e38c43bc406c75c51b343719d66b05cd44447a932f27dc108a8f78696f4ba6a51d39d729bfab2deef8b3c60d95c85271df681691999b12e8377dd0554f3b",
          "sha256": "ea0cbdbdad56c49cef0e2f8fe95914ecc0f2b43decfff20630ef3001a53a1209",
          "sha1": "6660876b6423b19d649d14cc20841c43cfbac5f6",
          "md5": "b55f01fb05370e421ad7c2b989aee770"
        }
      ]
    }
  ]
}
