{
  "formatVersion": "1.1",
  "component": {
    "group": "net.notjustanna.webview",
    "module": "webview_java-interop-gson",
    "version": "1.2.0+wv0.12.0-nightly.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.notjustanna.webview",
          "module": "webview_java-interop",
          "version": {
            "requires": "1.2.0+wv0.12.0-nightly.1"
          }
        }
      ],
      "files": [
        {
          "name": "webview_java-interop-gson-1.2.0+wv0.12.0-nightly.1.jar",
          "url": "webview_java-interop-gson-1.2.0+wv0.12.0-nightly.1.jar",
          "size": 3290,
          "sha512": "0e343b29030258fa1c338892a932871636f962a31f9cef663a017190b35d6b10847f7dcb9d48e6ed8b44897d53e09b11780f0e0e3b95aab111012499c571d2c3",
          "sha256": "d6e1d1b95e0b65524bd40c65e4320bf476f74df9a6ad83725d2432fa9ee73bad",
          "sha1": "ebbeabc7b74f7ab9ba914026e57fb4a252b29e5e",
          "md5": "d060a8ce0d83f17bc30c5731b6d882c6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.notjustanna.webview",
          "module": "webview_java",
          "version": {
            "requires": "1.2.0+wv0.12.0-nightly.1"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.17.0"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.17.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.12.1"
          }
        },
        {
          "group": "net.notjustanna.webview",
          "module": "webview_java-interop",
          "version": {
            "requires": "1.2.0+wv0.12.0-nightly.1"
          }
        }
      ],
      "files": [
        {
          "name": "webview_java-interop-gson-1.2.0+wv0.12.0-nightly.1.jar",
          "url": "webview_java-interop-gson-1.2.0+wv0.12.0-nightly.1.jar",
          "size": 3290,
          "sha512": "0e343b29030258fa1c338892a932871636f962a31f9cef663a017190b35d6b10847f7dcb9d48e6ed8b44897d53e09b11780f0e0e3b95aab111012499c571d2c3",
          "sha256": "d6e1d1b95e0b65524bd40c65e4320bf476f74df9a6ad83725d2432fa9ee73bad",
          "sha1": "ebbeabc7b74f7ab9ba914026e57fb4a252b29e5e",
          "md5": "d060a8ce0d83f17bc30c5731b6d882c6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webview_java-interop-gson-1.2.0+wv0.12.0-nightly.1-sources.jar",
          "url": "webview_java-interop-gson-1.2.0+wv0.12.0-nightly.1-sources.jar",
          "size": 2909,
          "sha512": "9c5d8359ef054c6da2c9c7b31ce67d50715886dc2920e3b5a3998c9e015c3095a55387dd3ee57f216c3285f642db7cfff8e0b9b578f92beca0befd9aeef49059",
          "sha256": "7e39e8d4a08c20fa4dd430336ca5248382202c5c8f72e93dfd7c25f6216a5e6b",
          "sha1": "826af0447eafd3a529081a411869460868befae7",
          "md5": "f0eeeebc69434719250fbd1f5337e517"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webview_java-interop-gson-1.2.0+wv0.12.0-nightly.1-javadoc.jar",
          "url": "webview_java-interop-gson-1.2.0+wv0.12.0-nightly.1-javadoc.jar",
          "size": 89737,
          "sha512": "799cd437053012a3b955b71edb1eaf08eabf918667b451c4611e30445254ede203839ea3db50dd1dacc2acbf6f9114467992b409f94d374fcecfed7ee0b3a253",
          "sha256": "ba37c6441ca4a7addb90b395f36afb9b4a1415dd0b4898f2f89b4a00b8c56e72",
          "sha1": "74a4d19d1e9eb6305688f2c262e9380fcad3e447",
          "md5": "b9d16d4106f6f3633480a79c575ba864"
        }
      ]
    }
  ]
}
