{
  "formatVersion": "1.1",
  "component": {
    "group": "net.notjustanna.webview",
    "module": "webview_java-interop-nanojson",
    "version": "1.3.0+wv0.12.0-nightly.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.notjustanna.webview",
          "module": "webview_java-interop",
          "version": {
            "requires": "1.3.0+wv0.12.0-nightly.1"
          }
        }
      ],
      "files": [
        {
          "name": "webview_java-interop-nanojson-1.3.0+wv0.12.0-nightly.1.jar",
          "url": "webview_java-interop-nanojson-1.3.0+wv0.12.0-nightly.1.jar",
          "size": 3238,
          "sha512": "03c8f3f64c1c38f722d78b070f4975e62426c64e3f0e6e3441c347ccb755b48019918e71d7fe19ef3d64cb8f13059662fb7ba0e3c3a5b540b99a115a7a91be82",
          "sha256": "11db992393d298b83893a9ead04117f1bfa32e2952a5a0d3dc9225785572d94d",
          "sha1": "ac6e844fdd767f721705a7c127b3973bde2eef34",
          "md5": "dcbb494596c5fbf2d15e40f3c4760bfc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.notjustanna.webview",
          "module": "webview_java",
          "version": {
            "requires": "1.3.0+wv0.12.0-nightly.1"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.17.0"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.17.0"
          }
        },
        {
          "group": "com.grack",
          "module": "nanojson",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "net.notjustanna.webview",
          "module": "webview_java-interop",
          "version": {
            "requires": "1.3.0+wv0.12.0-nightly.1"
          }
        }
      ],
      "files": [
        {
          "name": "webview_java-interop-nanojson-1.3.0+wv0.12.0-nightly.1.jar",
          "url": "webview_java-interop-nanojson-1.3.0+wv0.12.0-nightly.1.jar",
          "size": 3238,
          "sha512": "03c8f3f64c1c38f722d78b070f4975e62426c64e3f0e6e3441c347ccb755b48019918e71d7fe19ef3d64cb8f13059662fb7ba0e3c3a5b540b99a115a7a91be82",
          "sha256": "11db992393d298b83893a9ead04117f1bfa32e2952a5a0d3dc9225785572d94d",
          "sha1": "ac6e844fdd767f721705a7c127b3973bde2eef34",
          "md5": "dcbb494596c5fbf2d15e40f3c4760bfc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webview_java-interop-nanojson-1.3.0+wv0.12.0-nightly.1-sources.jar",
          "url": "webview_java-interop-nanojson-1.3.0+wv0.12.0-nightly.1-sources.jar",
          "size": 2606,
          "sha512": "e3e9b9d55b43ee819378d5fbede05bea4fb6ce9d42e6616cc1c9bebc96137be95a3837d448204a6b43f32baddf4103352efb892f2c219f11c9741e42e8c16e44",
          "sha256": "60c008dc16e456deac314e2c3b08119ee2cee9d709849810a56c0aea0402a2e4",
          "sha1": "b5539c3af29760b9751bbbe64449d08b34cf0671",
          "md5": "1599ef70e01e19d0f89c0ab049ef700d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webview_java-interop-nanojson-1.3.0+wv0.12.0-nightly.1-javadoc.jar",
          "url": "webview_java-interop-nanojson-1.3.0+wv0.12.0-nightly.1-javadoc.jar",
          "size": 89011,
          "sha512": "01bff5f12d203c7400e9cf9e823f505ca79b66fbcea9958ba792fadb31194c70b1f817e84a0e0c4ba62fb01785d626ad7096299718191abbc74cf60b032a73a4",
          "sha256": "f486a3550ed2fdf8bb10a93140ecddaac7b236a28878dfa927da9673d4df4c8c",
          "sha1": "6b3b5a3e7f320dc7861af6eb7460d1dd8132bf38",
          "md5": "8c9385639c7a128fda89d341b08caf69"
        }
      ]
    }
  ]
}
