{
  "formatVersion": "1.1",
  "component": {
    "group": "net.notjustanna.webview",
    "module": "webview_java-interop-nanojson",
    "version": "1.3.0+wv0.12.0-nightly.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.notjustanna.webview",
          "module": "webview_java-interop",
          "version": {
            "requires": "1.3.0+wv0.12.0-nightly.1"
          }
        }
      ],
      "files": [
        {
          "name": "webview_java-interop-nanojson-1.3.0+wv0.12.0-nightly.1.jar",
          "url": "webview_java-interop-nanojson-1.3.0+wv0.12.0-nightly.1.jar",
          "size": 3238,
          "sha512": "be375d4eec75e3a19cecb1bca0b9f9973a9ecaa45d80623b218acc66e0542dabe84bc7aec812e46962a406ca1d4cf8585962efb2ce5502b7e71ff74740034180",
          "sha256": "1ce63f251ccb04720bdc032c769afbc981ea891e2f2bfb6c34894fc5bf43200e",
          "sha1": "d9c2a335f5d19dfb517b02435843c1684c4c3899",
          "md5": "0abf44fa4a5fa54cae1dca2b53520a13"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.notjustanna.webview",
          "module": "webview_java",
          "version": {
            "requires": "1.3.0+wv0.12.0-nightly.1"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.17.0"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.17.0"
          }
        },
        {
          "group": "com.grack",
          "module": "nanojson",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "net.notjustanna.webview",
          "module": "webview_java-interop",
          "version": {
            "requires": "1.3.0+wv0.12.0-nightly.1"
          }
        }
      ],
      "files": [
        {
          "name": "webview_java-interop-nanojson-1.3.0+wv0.12.0-nightly.1.jar",
          "url": "webview_java-interop-nanojson-1.3.0+wv0.12.0-nightly.1.jar",
          "size": 3238,
          "sha512": "be375d4eec75e3a19cecb1bca0b9f9973a9ecaa45d80623b218acc66e0542dabe84bc7aec812e46962a406ca1d4cf8585962efb2ce5502b7e71ff74740034180",
          "sha256": "1ce63f251ccb04720bdc032c769afbc981ea891e2f2bfb6c34894fc5bf43200e",
          "sha1": "d9c2a335f5d19dfb517b02435843c1684c4c3899",
          "md5": "0abf44fa4a5fa54cae1dca2b53520a13"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webview_java-interop-nanojson-1.3.0+wv0.12.0-nightly.1-sources.jar",
          "url": "webview_java-interop-nanojson-1.3.0+wv0.12.0-nightly.1-sources.jar",
          "size": 2606,
          "sha512": "c2d85b8a6f02892c9716169750115174fc85c3644a0832f14f3e2de2d779989b75e3eae1240bcddb1d1c20704f68f75112c3d701377bd42072f13d99acf166cd",
          "sha256": "d7c57fdc71b43871819b03c6d9691280a0194d50abb7dbf9675ca0e23cf72083",
          "sha1": "2ed2f3d025269258ce29e78db43c02dfcdde83dd",
          "md5": "fc903794be8ef46385f2ade8a767fa97"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webview_java-interop-nanojson-1.3.0+wv0.12.0-nightly.1-javadoc.jar",
          "url": "webview_java-interop-nanojson-1.3.0+wv0.12.0-nightly.1-javadoc.jar",
          "size": 89011,
          "sha512": "dd277a9fc718b07b767fc8a50b4b45ddd3fa6761a1c682324436cff63d2c62634805fd52710df03acd97b11251b9a163866671fd05fab52f67d296e166427b4b",
          "sha256": "00f6a131d44d87e236b4c2477e64e7e60a89d9fe53f9c354e5c159c4c4e4e5d3",
          "sha1": "a39a12f10aa850ccb6dc5d9e736a942d9336601b",
          "md5": "c0d9b7b4d5c1a03a808cba5b36d31daa"
        }
      ]
    }
  ]
}
