{
  "formatVersion": "1.1",
  "component": {
    "group": "net.notjustanna.webview",
    "module": "webview_java-native-windows-x86",
    "version": "1.0.0+wv0.12.0-nightly.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "webview_java-native-windows-x86-1.0.0+wv0.12.0-nightly.1.jar",
          "url": "webview_java-native-windows-x86-1.0.0+wv0.12.0-nightly.1.jar",
          "size": 42802,
          "sha512": "19f92891552c0c452700c8af471c812849c4539e6b7c9de7e9447dce45493f93221c02b8919694abb67e1372f98ac0cadef9c57cbb8b595ef47c9a4fe026a737",
          "sha256": "24d51d1e793636b94d3db4a2446ebdc8c574ee9ef60f0ac548b73adf16b8294b",
          "sha1": "bc0248b12329c91e239bc53bfaaf2f45822eca4c",
          "md5": "e81e99cd00aadbce2f9b8dc1a255baec"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webview_java-native-windows-x86-1.0.0+wv0.12.0-nightly.1.jar",
          "url": "webview_java-native-windows-x86-1.0.0+wv0.12.0-nightly.1.jar",
          "size": 42802,
          "sha512": "19f92891552c0c452700c8af471c812849c4539e6b7c9de7e9447dce45493f93221c02b8919694abb67e1372f98ac0cadef9c57cbb8b595ef47c9a4fe026a737",
          "sha256": "24d51d1e793636b94d3db4a2446ebdc8c574ee9ef60f0ac548b73adf16b8294b",
          "sha1": "bc0248b12329c91e239bc53bfaaf2f45822eca4c",
          "md5": "e81e99cd00aadbce2f9b8dc1a255baec"
        }
      ]
    }
  ]
}
