{
  "formatVersion": "1.1",
  "component": {
    "group": "net.notjustanna.webview",
    "module": "webview_java-native-windows-x86-64",
    "version": "1.1.0+wv0.12.0-nightly.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "webview_java-native-windows-x86-64-1.1.0+wv0.12.0-nightly.1.jar",
          "url": "webview_java-native-windows-x86-64-1.1.0+wv0.12.0-nightly.1.jar",
          "size": 46811,
          "sha512": "b4d352cfd88e16afd3a2ded938cfd653dce2b857feaef9fa4ccff8f98e214311cc5f37800dd8669b6b6f7a78700d5caa2fcc7f292462975be22bd238cb73e26c",
          "sha256": "cda15e73d0ed783f7df575c2cebfe013caf67626346807ed47aaebed59b13692",
          "sha1": "45b964b96e57fae722c4196f50394093f53bdf7d",
          "md5": "6f88a1d829c772f458f8b6854bcf5bbe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webview_java-native-windows-x86-64-1.1.0+wv0.12.0-nightly.1.jar",
          "url": "webview_java-native-windows-x86-64-1.1.0+wv0.12.0-nightly.1.jar",
          "size": 46811,
          "sha512": "b4d352cfd88e16afd3a2ded938cfd653dce2b857feaef9fa4ccff8f98e214311cc5f37800dd8669b6b6f7a78700d5caa2fcc7f292462975be22bd238cb73e26c",
          "sha256": "cda15e73d0ed783f7df575c2cebfe013caf67626346807ed47aaebed59b13692",
          "sha1": "45b964b96e57fae722c4196f50394093f53bdf7d",
          "md5": "6f88a1d829c772f458f8b6854bcf5bbe"
        }
      ]
    }
  ]
}
