{
  "formatVersion": "1.1",
  "component": {
    "group": "net.notjustanna.webview",
    "module": "webview_java-interop-jackson",
    "version": "1.3.0+wv0.12.0-nightly.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.notjustanna.webview",
          "module": "webview_java-interop",
          "version": {
            "requires": "1.3.0+wv0.12.0-nightly.1"
          }
        }
      ],
      "files": [
        {
          "name": "webview_java-interop-jackson-1.3.0+wv0.12.0-nightly.1.jar",
          "url": "webview_java-interop-jackson-1.3.0+wv0.12.0-nightly.1.jar",
          "size": 3453,
          "sha512": "ba94a2b9a8af6420e7aeafa5e97904330c29f3814f6d3d220c9c45d5e24e077d4893d7a41413a6a9d1550d1b8e311a3eab9669c0971051b1215d7b07504c6929",
          "sha256": "00c02600db3af0e845ed7f49a3882c1b0b9ed8cee297f6886d0dac4b5eb20707",
          "sha1": "9a6ad38e3e5567706c3b93cf6826769d83844383",
          "md5": "ff15b71aff40877c1964de6a6bcda2df"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.notjustanna.webview",
          "module": "webview_java",
          "version": {
            "requires": "1.3.0+wv0.12.0-nightly.1"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.17.0"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.17.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.18.3"
          }
        },
        {
          "group": "net.notjustanna.webview",
          "module": "webview_java-interop",
          "version": {
            "requires": "1.3.0+wv0.12.0-nightly.1"
          }
        }
      ],
      "files": [
        {
          "name": "webview_java-interop-jackson-1.3.0+wv0.12.0-nightly.1.jar",
          "url": "webview_java-interop-jackson-1.3.0+wv0.12.0-nightly.1.jar",
          "size": 3453,
          "sha512": "ba94a2b9a8af6420e7aeafa5e97904330c29f3814f6d3d220c9c45d5e24e077d4893d7a41413a6a9d1550d1b8e311a3eab9669c0971051b1215d7b07504c6929",
          "sha256": "00c02600db3af0e845ed7f49a3882c1b0b9ed8cee297f6886d0dac4b5eb20707",
          "sha1": "9a6ad38e3e5567706c3b93cf6826769d83844383",
          "md5": "ff15b71aff40877c1964de6a6bcda2df"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webview_java-interop-jackson-1.3.0+wv0.12.0-nightly.1-sources.jar",
          "url": "webview_java-interop-jackson-1.3.0+wv0.12.0-nightly.1-sources.jar",
          "size": 3037,
          "sha512": "148ce56f0f4656f41aacb0cc7126cd742b99a058541f02d95195f89ec4cea1e514d6eec6b2e6be5de89c99fb056431e0bb3ca81d94fc311fd43671729d8233d2",
          "sha256": "387cc97addd2e6cf444f8d592e50a8bf9c95dee5e9a117914ba00a102bb73a63",
          "sha1": "c6e562c4589f76cfa76db5bb0bce4a195e20bb1e",
          "md5": "43972d95762579a3f202788911ec0832"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webview_java-interop-jackson-1.3.0+wv0.12.0-nightly.1-javadoc.jar",
          "url": "webview_java-interop-jackson-1.3.0+wv0.12.0-nightly.1-javadoc.jar",
          "size": 89905,
          "sha512": "59a785314a4a714dba24adae2846426f9401383cb309ce2afa930e5ab5b2ded86f5abe67e7880cff3100f9196b49607b868aa8458b5376003d0b762f4fbf2670",
          "sha256": "64b166b710a7c293ce43f85531bfed89cab1b984e898ecf4acffdc231b6cd352",
          "sha1": "60d9196c94afc17d413997c511ffcb457611f494",
          "md5": "8ba61d9f5ce8c93ed31044e47c23cd56"
        }
      ]
    }
  ]
}
