{
  "formatVersion": "1.1",
  "component": {
    "group": "net.notjustanna.webview",
    "module": "webview_java",
    "version": "1.3.0+wv0.12.0-nightly.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "webview_java-1.3.0+wv0.12.0-nightly.1.jar",
          "url": "webview_java-1.3.0+wv0.12.0-nightly.1.jar",
          "size": 22434,
          "sha512": "42b1941551ba409ef7c9fa218e32eabe685e93301efe3335d5076fa8299d2c0365d7394dd35923d5c83e8e257db57572cccfc045c4e917673e992599c3ac97e0",
          "sha256": "793d025c7c1f3a6ad9de95dd0fda1e0156d34e424ba0ed277f7b19fd99a169f0",
          "sha1": "b90649a510c69c7bf3770d49d074290b1f6447f2",
          "md5": "7c731c51cd2573e48a33320ed7fdda42"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.17.0"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.17.0"
          }
        }
      ],
      "files": [
        {
          "name": "webview_java-1.3.0+wv0.12.0-nightly.1.jar",
          "url": "webview_java-1.3.0+wv0.12.0-nightly.1.jar",
          "size": 22434,
          "sha512": "42b1941551ba409ef7c9fa218e32eabe685e93301efe3335d5076fa8299d2c0365d7394dd35923d5c83e8e257db57572cccfc045c4e917673e992599c3ac97e0",
          "sha256": "793d025c7c1f3a6ad9de95dd0fda1e0156d34e424ba0ed277f7b19fd99a169f0",
          "sha1": "b90649a510c69c7bf3770d49d074290b1f6447f2",
          "md5": "7c731c51cd2573e48a33320ed7fdda42"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webview_java-1.3.0+wv0.12.0-nightly.1-sources.jar",
          "url": "webview_java-1.3.0+wv0.12.0-nightly.1-sources.jar",
          "size": 15962,
          "sha512": "6dcb0abe363167e84614684c2d081c44e79901518e8e12d53d6e8ecc150efb38ba2996d2e434a7dbf4080925769e84084c03f5401bef1f60cb2a055fe4a41bc1",
          "sha256": "868f7c2bf593a9944592caf09cba9cfda66f1ed303c47238e9e3e4ac0e230a30",
          "sha1": "5c4dda87497d0f990ed4b4c41306c1c0bf38b5ae",
          "md5": "5a2aa16c7723c162c0b14f25d2280a33"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webview_java-1.3.0+wv0.12.0-nightly.1-javadoc.jar",
          "url": "webview_java-1.3.0+wv0.12.0-nightly.1-javadoc.jar",
          "size": 152214,
          "sha512": "c2fd73129b7bb56d5b2b8cf3bf7ed6700f5ff3caebdde0296de6c788e7cc59deb292cb7de7b87b3ae7410b25a485c68e00c28c4f2ad4e1b823fc403cf878ca2b",
          "sha256": "6ec437b4551817ddb10f839080f46ad29fb594348125a88914ca527a0cab0421",
          "sha1": "179ffaa3ae866addda6470c7af7ac1e8315038d5",
          "md5": "da79983f0a87db5c7f6d5416189d2a47"
        }
      ]
    }
  ]
}
