{
  "formatVersion": "1.1",
  "component": {
    "group": "net.notjustanna.webview",
    "module": "webview_java",
    "version": "1.3.0+wv0.12.0-nightly.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "webview_java-1.3.0+wv0.12.0-nightly.1.jar",
          "url": "webview_java-1.3.0+wv0.12.0-nightly.1.jar",
          "size": 22434,
          "sha512": "aaf3c7b42437aea630106baaf837090d4f6d40450e6cac0e0b8d1362c994a63e13cc806662c55217463f66250a20ff2b51647a93b40d012cbf32cc31cb052865",
          "sha256": "4455ff41070f0df93df3b45168dab490c81f7de1462464cadd3e848d26d05763",
          "sha1": "51909564760609fdc92ca768c9200150f285cb90",
          "md5": "c196d4efc59a06b1cedf05272373e909"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.17.0"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.17.0"
          }
        }
      ],
      "files": [
        {
          "name": "webview_java-1.3.0+wv0.12.0-nightly.1.jar",
          "url": "webview_java-1.3.0+wv0.12.0-nightly.1.jar",
          "size": 22434,
          "sha512": "aaf3c7b42437aea630106baaf837090d4f6d40450e6cac0e0b8d1362c994a63e13cc806662c55217463f66250a20ff2b51647a93b40d012cbf32cc31cb052865",
          "sha256": "4455ff41070f0df93df3b45168dab490c81f7de1462464cadd3e848d26d05763",
          "sha1": "51909564760609fdc92ca768c9200150f285cb90",
          "md5": "c196d4efc59a06b1cedf05272373e909"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webview_java-1.3.0+wv0.12.0-nightly.1-sources.jar",
          "url": "webview_java-1.3.0+wv0.12.0-nightly.1-sources.jar",
          "size": 15962,
          "sha512": "dfa5318878b6d26e7a0343fcd8348ea2a4c93fcb3c5ed72240cc11cb866bc71ea47165d6f57b45f23b46abec123b8f762ccae0915ed9b2b8171548862d69565d",
          "sha256": "6e14d38225120874f288db1f45311ff81e1cd3b8d2277cb130dda7eab279ad08",
          "sha1": "bd84ac78b84da4f9421899716a5dca5504543220",
          "md5": "e61df4d7fcb4ad8bed7299cb90dbd9ee"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webview_java-1.3.0+wv0.12.0-nightly.1-javadoc.jar",
          "url": "webview_java-1.3.0+wv0.12.0-nightly.1-javadoc.jar",
          "size": 152214,
          "sha512": "2102938eed2cc90e74e2f8c2dc09fc382304c643024aff5a6ebded496109a3a6e156d4abc012070edd2608031de4b124d7961dc5aa2051e9b195095b8ba9a55f",
          "sha256": "f6afd4ec09decc21a63595c4fb7bc8868823030fab0706c424de28ff8420828a",
          "sha1": "df6fed0496f295daa7e7e14e3768c3e76ccaf462",
          "md5": "88c1c01e5e064b4f35132dd2a08d6cef"
        }
      ]
    }
  ]
}
