{
  "formatVersion": "1.1",
  "component": {
    "group": "net.notjustanna.webview",
    "module": "webview_java-native-windows-arm64",
    "version": "1.5.0+wv0.12.0-nightly.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "webview_java-native-windows-arm64-1.5.0+wv0.12.0-nightly.1.jar",
          "url": "webview_java-native-windows-arm64-1.5.0+wv0.12.0-nightly.1.jar",
          "size": 43048,
          "sha512": "9540a9244fea5e9980f6b7ce236a818b37882e6667292b13b9cf651ccf5c1d2e5406ba17030120b6e159ae1a410200e7733b3bbe585c6dc18e7d858df2162f40",
          "sha256": "1368a2b20ba9c46a0907ce26161f9e5d5975ff8a61dc30ae1a084e6bffa515c1",
          "sha1": "9d6d7a1f18a94232be001b218ff93736dd502733",
          "md5": "c5c5258ce9ea1bb4046ef3f740ef7e9d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webview_java-native-windows-arm64-1.5.0+wv0.12.0-nightly.1.jar",
          "url": "webview_java-native-windows-arm64-1.5.0+wv0.12.0-nightly.1.jar",
          "size": 43048,
          "sha512": "9540a9244fea5e9980f6b7ce236a818b37882e6667292b13b9cf651ccf5c1d2e5406ba17030120b6e159ae1a410200e7733b3bbe585c6dc18e7d858df2162f40",
          "sha256": "1368a2b20ba9c46a0907ce26161f9e5d5975ff8a61dc30ae1a084e6bffa515c1",
          "sha1": "9d6d7a1f18a94232be001b218ff93736dd502733",
          "md5": "c5c5258ce9ea1bb4046ef3f740ef7e9d"
        }
      ]
    }
  ]
}
