{
  "formatVersion": "1.1",
  "component": {
    "group": "net.notjustanna.webview",
    "module": "webview_java-all-natives",
    "version": "1.0.0+wv0.12.0-nightly.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "webview_java-all-natives-1.0.0+wv0.12.0-nightly.1.jar",
          "url": "webview_java-all-natives-1.0.0+wv0.12.0-nightly.1.jar",
          "size": 261,
          "sha512": "baf0d721c9b90f41e93d43a6366ecd7820a030c613958e382d984d3d56b858261f00430cb85dede721c77af558712977b3ab9295423b2f74cfbd5ef1c5b149cf",
          "sha256": "23066cb5b3334fcbebebf878c84b2461f694235ca922279176efafd524ddb590",
          "sha1": "3bf40ae0513e8f7f449a3ec53c6f1514f44771dc",
          "md5": "e12a8f319047cb1827ed499b23f90c17"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.notjustanna.webview",
          "module": "webview_java-native-darwin",
          "version": {
            "requires": "1.0.0+wv0.12.0-nightly.1"
          }
        },
        {
          "group": "net.notjustanna.webview",
          "module": "webview_java-native-linux-x86-64",
          "version": {
            "requires": "1.0.0+wv0.12.0-nightly.1"
          }
        },
        {
          "group": "net.notjustanna.webview",
          "module": "webview_java-native-windows-arm64",
          "version": {
            "requires": "1.0.0+wv0.12.0-nightly.1"
          }
        },
        {
          "group": "net.notjustanna.webview",
          "module": "webview_java-native-windows-x86",
          "version": {
            "requires": "1.0.0+wv0.12.0-nightly.1"
          }
        },
        {
          "group": "net.notjustanna.webview",
          "module": "webview_java-native-windows-x86-64",
          "version": {
            "requires": "1.0.0+wv0.12.0-nightly.1"
          }
        }
      ],
      "files": [
        {
          "name": "webview_java-all-natives-1.0.0+wv0.12.0-nightly.1.jar",
          "url": "webview_java-all-natives-1.0.0+wv0.12.0-nightly.1.jar",
          "size": 261,
          "sha512": "baf0d721c9b90f41e93d43a6366ecd7820a030c613958e382d984d3d56b858261f00430cb85dede721c77af558712977b3ab9295423b2f74cfbd5ef1c5b149cf",
          "sha256": "23066cb5b3334fcbebebf878c84b2461f694235ca922279176efafd524ddb590",
          "sha1": "3bf40ae0513e8f7f449a3ec53c6f1514f44771dc",
          "md5": "e12a8f319047cb1827ed499b23f90c17"
        }
      ]
    }
  ]
}
