{
  "formatVersion": "1.1",
  "component": {
    "group": "net.notjustanna.webview",
    "module": "webview_java-interop-nanojson",
    "version": "1.4.0+wv0.12.0-nightly.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.notjustanna.webview",
          "module": "webview_java-interop",
          "version": {
            "requires": "1.4.0+wv0.12.0-nightly.1"
          }
        }
      ],
      "files": [
        {
          "name": "webview_java-interop-nanojson-1.4.0+wv0.12.0-nightly.1.jar",
          "url": "webview_java-interop-nanojson-1.4.0+wv0.12.0-nightly.1.jar",
          "size": 3238,
          "sha512": "a5961b277dad17d469f1497866cdb9b996bbecbde7dfe104dd7f61c947f4ae7e324140f9632bfcf5df1f2029cc2688aeaa7e0594da4e06c06d255713def89b4b",
          "sha256": "0c50f8e33064866c12fe7e189aadca2ceab52b7d8c606896f08b12534f4cd11f",
          "sha1": "7b6601c38f5894995e989882c54dea7f34f58c38",
          "md5": "7b6f749da67d30f3a4cf91e5ba9e32e4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.notjustanna.webview",
          "module": "webview_java",
          "version": {
            "requires": "1.4.0+wv0.12.0-nightly.1"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.17.0"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.17.0"
          }
        },
        {
          "group": "com.grack",
          "module": "nanojson",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "net.notjustanna.webview",
          "module": "webview_java-interop",
          "version": {
            "requires": "1.4.0+wv0.12.0-nightly.1"
          }
        }
      ],
      "files": [
        {
          "name": "webview_java-interop-nanojson-1.4.0+wv0.12.0-nightly.1.jar",
          "url": "webview_java-interop-nanojson-1.4.0+wv0.12.0-nightly.1.jar",
          "size": 3238,
          "sha512": "a5961b277dad17d469f1497866cdb9b996bbecbde7dfe104dd7f61c947f4ae7e324140f9632bfcf5df1f2029cc2688aeaa7e0594da4e06c06d255713def89b4b",
          "sha256": "0c50f8e33064866c12fe7e189aadca2ceab52b7d8c606896f08b12534f4cd11f",
          "sha1": "7b6601c38f5894995e989882c54dea7f34f58c38",
          "md5": "7b6f749da67d30f3a4cf91e5ba9e32e4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webview_java-interop-nanojson-1.4.0+wv0.12.0-nightly.1-sources.jar",
          "url": "webview_java-interop-nanojson-1.4.0+wv0.12.0-nightly.1-sources.jar",
          "size": 2606,
          "sha512": "3abf29876b7882be2b14d7c8bd492180d1fc1c23d2f8fe50eccdf8ce0828774160a99ec9c234b9d988c383237aacca8c81e73a9b62fbcf9882079a21ad7b340f",
          "sha256": "2c6e4e770aa786513a48c3afb250db66888a58ea49124771a54f9fe94d682644",
          "sha1": "10988570e94d4a69507c0fab4d3699696756f791",
          "md5": "6f1b5c8e41802fd8924a10eb7f3bf337"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webview_java-interop-nanojson-1.4.0+wv0.12.0-nightly.1-javadoc.jar",
          "url": "webview_java-interop-nanojson-1.4.0+wv0.12.0-nightly.1-javadoc.jar",
          "size": 89019,
          "sha512": "b97e8848a7468a777f809455ad828c1ad056fa333428320a4cdf27b7f4b0bff7a6b3e99ad1e9df2dd8427edbea6b4b4bcc7c4f71bc0e7b661481f54ab4459227",
          "sha256": "f1b9bf7f51e8af5016cc215b71cf48b2904785db0ebe6adf38ca582413b05603",
          "sha1": "9d730535cf3246844eee1c5c04ce172b1f1baf84",
          "md5": "5e8e99b1af5136b034b63c0bb69cbc85"
        }
      ]
    }
  ]
}
