{
  "formatVersion": "1.1",
  "component": {
    "group": "net.notjustanna.webview",
    "module": "webview_java-native-windows-x86",
    "version": "1.3.0+wv0.12.0-nightly.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "webview_java-native-windows-x86-1.3.0+wv0.12.0-nightly.1.jar",
          "url": "webview_java-native-windows-x86-1.3.0+wv0.12.0-nightly.1.jar",
          "size": 42802,
          "sha512": "e7b09c89de7f3bb461004f1165e36b15d2ff6dcc9b6ba7443eb1c7ff45d495c7fb3817446d4103ee26f785842ee693b6a46f04b096722a05b232f23ba4c7c716",
          "sha256": "2c4c213fae5b5c1f9c6e27194944b51945e87c55c978763e27d10ae6e4d43474",
          "sha1": "8c1d8cc62916e8073b7ce6cae6fcfcbad68e2807",
          "md5": "319a09dd0ad6e7a4f1e0f76c6057d452"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webview_java-native-windows-x86-1.3.0+wv0.12.0-nightly.1.jar",
          "url": "webview_java-native-windows-x86-1.3.0+wv0.12.0-nightly.1.jar",
          "size": 42802,
          "sha512": "e7b09c89de7f3bb461004f1165e36b15d2ff6dcc9b6ba7443eb1c7ff45d495c7fb3817446d4103ee26f785842ee693b6a46f04b096722a05b232f23ba4c7c716",
          "sha256": "2c4c213fae5b5c1f9c6e27194944b51945e87c55c978763e27d10ae6e4d43474",
          "sha1": "8c1d8cc62916e8073b7ce6cae6fcfcbad68e2807",
          "md5": "319a09dd0ad6e7a4f1e0f76c6057d452"
        }
      ]
    }
  ]
}
