{
  "formatVersion": "1.1",
  "component": {
    "group": "net.notjustanna.webview",
    "module": "webview_java-native-windows-x86-64",
    "version": "1.0.0+wv0.12.0-nightly.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "webview_java-native-windows-x86-64-1.0.0+wv0.12.0-nightly.1.jar",
          "url": "webview_java-native-windows-x86-64-1.0.0+wv0.12.0-nightly.1.jar",
          "size": 46811,
          "sha512": "e67293f26f98bbc71af7018cdf0b8b05d8efe58e5d3704e58d43166579597bdd5b3127233b0985073caa7b6a02f123fc98ec2b94c84df1290440bb9d0c4e94d2",
          "sha256": "b9590f3800dc2cc02330b175e6d0468d292fb3b682104996dc8202a94cdc4f74",
          "sha1": "22897196e509e66bf0d34f60f583df213ddbc21e",
          "md5": "bd5597c244646c26ee00deb81989e98f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webview_java-native-windows-x86-64-1.0.0+wv0.12.0-nightly.1.jar",
          "url": "webview_java-native-windows-x86-64-1.0.0+wv0.12.0-nightly.1.jar",
          "size": 46811,
          "sha512": "e67293f26f98bbc71af7018cdf0b8b05d8efe58e5d3704e58d43166579597bdd5b3127233b0985073caa7b6a02f123fc98ec2b94c84df1290440bb9d0c4e94d2",
          "sha256": "b9590f3800dc2cc02330b175e6d0468d292fb3b682104996dc8202a94cdc4f74",
          "sha1": "22897196e509e66bf0d34f60f583df213ddbc21e",
          "md5": "bd5597c244646c26ee00deb81989e98f"
        }
      ]
    }
  ]
}
