{
  "formatVersion": "1.1",
  "component": {
    "group": "net.notjustanna.webview",
    "module": "webview_java-native-windows-x86-64",
    "version": "1.0.0+wv0.12.0-nightly.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "webview_java-native-windows-x86-64-1.0.0+wv0.12.0-nightly.1.jar",
          "url": "webview_java-native-windows-x86-64-1.0.0+wv0.12.0-nightly.1.jar",
          "size": 46811,
          "sha512": "cf45eef9db026672f96c500a8eb52118714598ca3e9d2e27cef7d1977393c91ccc68a1f3cd321035b8979882d0b9593188062252a6b85420ab1bc65050d17de7",
          "sha256": "c053b1b890e6b37ca7f46fbd3ad04bc704d87de6983671d64df582ebee854c1c",
          "sha1": "6fc76e28503232d48f78615d87155df0dfa12584",
          "md5": "d7d36f05872681b6aa24eac0292dd85f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webview_java-native-windows-x86-64-1.0.0+wv0.12.0-nightly.1.jar",
          "url": "webview_java-native-windows-x86-64-1.0.0+wv0.12.0-nightly.1.jar",
          "size": 46811,
          "sha512": "cf45eef9db026672f96c500a8eb52118714598ca3e9d2e27cef7d1977393c91ccc68a1f3cd321035b8979882d0b9593188062252a6b85420ab1bc65050d17de7",
          "sha256": "c053b1b890e6b37ca7f46fbd3ad04bc704d87de6983671d64df582ebee854c1c",
          "sha1": "6fc76e28503232d48f78615d87155df0dfa12584",
          "md5": "d7d36f05872681b6aa24eac0292dd85f"
        }
      ]
    }
  ]
}
