{
  "formatVersion": "1.1",
  "component": {
    "group": "net.notjustanna.webview",
    "module": "webview_java-native-darwin",
    "version": "1.5.0+wv0.12.0-nightly.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "webview_java-native-darwin-1.5.0+wv0.12.0-nightly.1.jar",
          "url": "webview_java-native-darwin-1.5.0+wv0.12.0-nightly.1.jar",
          "size": 76796,
          "sha512": "45fb930ad38962cac36ac7213b62ff9779b578bd15e024304d076c2b1907f5bed2dc78e9c134dcc53a5026600c5f8a856937d5749fbffa83f77cc219c751d067",
          "sha256": "391f7bb01c2b8b005536ac4589978f2a858bcf2b128ae8c299fd827b886cdeae",
          "sha1": "d7fb7d8f2c3e637aecffb984b05bd73c0746fc62",
          "md5": "2ead40b7a2dd2acf941b743362b3fc28"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webview_java-native-darwin-1.5.0+wv0.12.0-nightly.1.jar",
          "url": "webview_java-native-darwin-1.5.0+wv0.12.0-nightly.1.jar",
          "size": 76796,
          "sha512": "45fb930ad38962cac36ac7213b62ff9779b578bd15e024304d076c2b1907f5bed2dc78e9c134dcc53a5026600c5f8a856937d5749fbffa83f77cc219c751d067",
          "sha256": "391f7bb01c2b8b005536ac4589978f2a858bcf2b128ae8c299fd827b886cdeae",
          "sha1": "d7fb7d8f2c3e637aecffb984b05bd73c0746fc62",
          "md5": "2ead40b7a2dd2acf941b743362b3fc28"
        }
      ]
    }
  ]
}
