{
  "formatVersion": "1.1",
  "component": {
    "group": "net.notjustanna.webview",
    "module": "webview_java-native-windows-arm64",
    "version": "1.3.0+wv0.12.0-nightly.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "webview_java-native-windows-arm64-1.3.0+wv0.12.0-nightly.1.jar",
          "url": "webview_java-native-windows-arm64-1.3.0+wv0.12.0-nightly.1.jar",
          "size": 43048,
          "sha512": "b919b5a30356c6a29c1a07126004555994a724af0498f736d951dc97993f21810eb0b8866e9c4c98aa9790d6a8e6b2db122508007c02ac79983c1a24d705b36a",
          "sha256": "a419d56f8b1be7521a41dc43998e7c77b71deca0478aa2fad46e643706c5c06d",
          "sha1": "5c67c79f55e1c825b911ecb8a3ae2a09a79c8c14",
          "md5": "2fe3a96299016c7cb5258dd2d6bae402"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webview_java-native-windows-arm64-1.3.0+wv0.12.0-nightly.1.jar",
          "url": "webview_java-native-windows-arm64-1.3.0+wv0.12.0-nightly.1.jar",
          "size": 43048,
          "sha512": "b919b5a30356c6a29c1a07126004555994a724af0498f736d951dc97993f21810eb0b8866e9c4c98aa9790d6a8e6b2db122508007c02ac79983c1a24d705b36a",
          "sha256": "a419d56f8b1be7521a41dc43998e7c77b71deca0478aa2fad46e643706c5c06d",
          "sha1": "5c67c79f55e1c825b911ecb8a3ae2a09a79c8c14",
          "md5": "2fe3a96299016c7cb5258dd2d6bae402"
        }
      ]
    }
  ]
}
