{
  "formatVersion": "1.1",
  "component": {
    "group": "net.notjustanna.webview",
    "module": "webview_java-native-windows-arm64",
    "version": "1.3.0+wv0.12.0-nightly.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "webview_java-native-windows-arm64-1.3.0+wv0.12.0-nightly.1.jar",
          "url": "webview_java-native-windows-arm64-1.3.0+wv0.12.0-nightly.1.jar",
          "size": 43048,
          "sha512": "261c45e04ac366a169576b93134abe5f83d1ae2d96fee2d92aa614e3821953c514cb8ab0ad4d52a638c831075d8684ef54b18a1974b7a8f605e50fda687459af",
          "sha256": "9b4712a49678a4727fde36f4842bafcc5844265178159d8845c15eb0a900433d",
          "sha1": "f29e506ca2ac408f7f75b97d4996358d23b65335",
          "md5": "846ceae6389e32980a21c5a7c211918d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webview_java-native-windows-arm64-1.3.0+wv0.12.0-nightly.1.jar",
          "url": "webview_java-native-windows-arm64-1.3.0+wv0.12.0-nightly.1.jar",
          "size": 43048,
          "sha512": "261c45e04ac366a169576b93134abe5f83d1ae2d96fee2d92aa614e3821953c514cb8ab0ad4d52a638c831075d8684ef54b18a1974b7a8f605e50fda687459af",
          "sha256": "9b4712a49678a4727fde36f4842bafcc5844265178159d8845c15eb0a900433d",
          "sha1": "f29e506ca2ac408f7f75b97d4996358d23b65335",
          "md5": "846ceae6389e32980a21c5a7c211918d"
        }
      ]
    }
  ]
}
