{
  "formatVersion": "1.1",
  "component": {
    "group": "net.notjustanna.webview",
    "module": "webview_java",
    "version": "1.0.0+wv0.12.0-nightly.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "webview_java-1.0.0+wv0.12.0-nightly.1.jar",
          "url": "webview_java-1.0.0+wv0.12.0-nightly.1.jar",
          "size": 17932,
          "sha512": "13d94b6ed9c4a448a679d86b481787fe9fce09b6f2c3acd62e4a3069a4c024b29dceada29d439f2a45e4ecb425ebe14a553dee9b54c868772a5b2e48cc83e131",
          "sha256": "f95dedb59814dbf8944479ef1acea0f2a19530466732ebdbdedd4bf549598bdb",
          "sha1": "94baf1a9464ecbfb4b15a09aecafb4624d003620",
          "md5": "829d9063ab00461f638956286a42559c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.17.0"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.17.0"
          }
        }
      ],
      "files": [
        {
          "name": "webview_java-1.0.0+wv0.12.0-nightly.1.jar",
          "url": "webview_java-1.0.0+wv0.12.0-nightly.1.jar",
          "size": 17932,
          "sha512": "13d94b6ed9c4a448a679d86b481787fe9fce09b6f2c3acd62e4a3069a4c024b29dceada29d439f2a45e4ecb425ebe14a553dee9b54c868772a5b2e48cc83e131",
          "sha256": "f95dedb59814dbf8944479ef1acea0f2a19530466732ebdbdedd4bf549598bdb",
          "sha1": "94baf1a9464ecbfb4b15a09aecafb4624d003620",
          "md5": "829d9063ab00461f638956286a42559c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webview_java-1.0.0+wv0.12.0-nightly.1-sources.jar",
          "url": "webview_java-1.0.0+wv0.12.0-nightly.1-sources.jar",
          "size": 13399,
          "sha512": "1bdec78f57cfec6721b0789c348fa64176a5cfa873c69b8c98d1ef84a684fc61fc57be1a91c3bec4ac716d273228941df776137d027ca60d223a8b38f57059e2",
          "sha256": "7d8ed3b61930c096e264aa6c5bd009bea0bead930a1d7923e76546635de9828e",
          "sha1": "93bf99a9c0c422aadd012f06be9d6dff489ac478",
          "md5": "9274a5894174ab8445f6fbaea4ef5d7c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webview_java-1.0.0+wv0.12.0-nightly.1-javadoc.jar",
          "url": "webview_java-1.0.0+wv0.12.0-nightly.1-javadoc.jar",
          "size": 131599,
          "sha512": "05828e2293f837f7b5b7dacc671b88316fbcf39fe57d5bb62cdd0786865ee1b990d7de84567f89a1e8aaa197963eb229f1ceeee9479bc94263080e45fccf29b9",
          "sha256": "dac18a9a0c22d55e716a25f88fff756f351a67af9c77831ff599c19188d25139",
          "sha1": "cf048331144c9d3f6c338890d8d4cb63fecbf1e4",
          "md5": "5a90eac0e1edc85afd9bacf9c445fe5a"
        }
      ]
    }
  ]
}
