{
  "formatVersion": "1.1",
  "component": {
    "group": "net.notjustanna.webview",
    "module": "webview_java",
    "version": "1.0.0+wv0.12.0-nightly.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "webview_java-1.0.0+wv0.12.0-nightly.1.jar",
          "url": "webview_java-1.0.0+wv0.12.0-nightly.1.jar",
          "size": 17932,
          "sha512": "ba07f50ff4d38f445dcd08f9da7ea6c42f899c585ab7f6d083e201fce511e9828b209dbf7b48db5de20a01719ffcbff8ead2216d1f9a8df042eb6e03aa0fd995",
          "sha256": "8d4d5fbe4d5c8ae689f4197fcc53e660a05e412f40cd4d7642946a008aa7cd12",
          "sha1": "4194aca0392122f69060959327e755cc6dac0b92",
          "md5": "ff21291c96b106ece4dcd3fe3173a16b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.17.0"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.17.0"
          }
        }
      ],
      "files": [
        {
          "name": "webview_java-1.0.0+wv0.12.0-nightly.1.jar",
          "url": "webview_java-1.0.0+wv0.12.0-nightly.1.jar",
          "size": 17932,
          "sha512": "ba07f50ff4d38f445dcd08f9da7ea6c42f899c585ab7f6d083e201fce511e9828b209dbf7b48db5de20a01719ffcbff8ead2216d1f9a8df042eb6e03aa0fd995",
          "sha256": "8d4d5fbe4d5c8ae689f4197fcc53e660a05e412f40cd4d7642946a008aa7cd12",
          "sha1": "4194aca0392122f69060959327e755cc6dac0b92",
          "md5": "ff21291c96b106ece4dcd3fe3173a16b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webview_java-1.0.0+wv0.12.0-nightly.1-sources.jar",
          "url": "webview_java-1.0.0+wv0.12.0-nightly.1-sources.jar",
          "size": 13399,
          "sha512": "9e471881563a68f775fa2098aca0299d13f0107b2012b12e6075fe23a8231f0448fe77ed280b324756fb22d3b812d5daa6a15ed33d92fe7e579acdd98d0b524f",
          "sha256": "09dd7fdc79f591f0545e7de6d93ec7720d13a7aeddda2691454621cfd82a8350",
          "sha1": "c28d8e3e6278b88da4d8163d09d98c00cb3b4f14",
          "md5": "db5a6be34c8dc88cf063563068f02960"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webview_java-1.0.0+wv0.12.0-nightly.1-javadoc.jar",
          "url": "webview_java-1.0.0+wv0.12.0-nightly.1-javadoc.jar",
          "size": 131599,
          "sha512": "e1d6605c2027b47c7605701066416dba830ae31f05b467cf53c7954a3c787827792aa4893d90e5660a1083a463a196e2239c04ec363173f8e531d179d79f1845",
          "sha256": "0bd3891998fe723f5945fea4865d2c7610bb197ac7a321e97635955018c16276",
          "sha1": "9ddad1c477de24ecde05aa85f3b5786d52cdd36f",
          "md5": "d176493b968757fc1fca3c45787fd169"
        }
      ]
    }
  ]
}
