{
  "formatVersion": "1.1",
  "component": {
    "group": "net.notjustanna.webview",
    "module": "webview_java-native-darwin",
    "version": "1.3.0+wv0.12.0-nightly.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "webview_java-native-darwin-1.3.0+wv0.12.0-nightly.1.jar",
          "url": "webview_java-native-darwin-1.3.0+wv0.12.0-nightly.1.jar",
          "size": 76796,
          "sha512": "43b75e549757147b1d6ed42c0a4c082d0a5584b80f8f7249cb9774597f456fb9cbb1ac4ddf50b75bf9fb6baa30b7f327531ca0cb2f9a23a7b130129c1ac5a5f7",
          "sha256": "a43f9577fa28fe98dfe0e2589d82031ef34dc61161d3cc91a06bfa9dc3ff8319",
          "sha1": "5296cff126c670b0ca1f775293536dfcee8d52ad",
          "md5": "8e985d8cd23220553d7b5ea158fa58b7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webview_java-native-darwin-1.3.0+wv0.12.0-nightly.1.jar",
          "url": "webview_java-native-darwin-1.3.0+wv0.12.0-nightly.1.jar",
          "size": 76796,
          "sha512": "43b75e549757147b1d6ed42c0a4c082d0a5584b80f8f7249cb9774597f456fb9cbb1ac4ddf50b75bf9fb6baa30b7f327531ca0cb2f9a23a7b130129c1ac5a5f7",
          "sha256": "a43f9577fa28fe98dfe0e2589d82031ef34dc61161d3cc91a06bfa9dc3ff8319",
          "sha1": "5296cff126c670b0ca1f775293536dfcee8d52ad",
          "md5": "8e985d8cd23220553d7b5ea158fa58b7"
        }
      ]
    }
  ]
}
