{
  "formatVersion": "1.1",
  "component": {
    "group": "net.notjustanna.webview",
    "module": "webview_java-all-natives",
    "version": "1.3.1+wv0.12.0-nightly.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "webview_java-all-natives-1.3.1+wv0.12.0-nightly.1.jar",
          "url": "webview_java-all-natives-1.3.1+wv0.12.0-nightly.1.jar",
          "size": 261,
          "sha512": "d40d091aec95beef7eac4f47de90ab91a989b656a94c065d097ceb4b94507f2fc4709d838af6f071727217190c07e1fb4efaaaceb4e8ed0ae2057c997034be4f",
          "sha256": "574a561acafd9685a92f10bb7fcce336fdd28c5d01889490b8217185af83260e",
          "sha1": "e37be2cab5bd0f412c17e6d36d94532a2708e85b",
          "md5": "41c9a47ed490bdb0115160a415bcf651"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.notjustanna.webview",
          "module": "webview_java-native-darwin",
          "version": {
            "requires": "1.3.1+wv0.12.0-nightly.1"
          }
        },
        {
          "group": "net.notjustanna.webview",
          "module": "webview_java-native-linux-x86-64",
          "version": {
            "requires": "1.3.1+wv0.12.0-nightly.1"
          }
        },
        {
          "group": "net.notjustanna.webview",
          "module": "webview_java-native-windows-arm64",
          "version": {
            "requires": "1.3.1+wv0.12.0-nightly.1"
          }
        },
        {
          "group": "net.notjustanna.webview",
          "module": "webview_java-native-windows-x86",
          "version": {
            "requires": "1.3.1+wv0.12.0-nightly.1"
          }
        },
        {
          "group": "net.notjustanna.webview",
          "module": "webview_java-native-windows-x86-64",
          "version": {
            "requires": "1.3.1+wv0.12.0-nightly.1"
          }
        }
      ],
      "files": [
        {
          "name": "webview_java-all-natives-1.3.1+wv0.12.0-nightly.1.jar",
          "url": "webview_java-all-natives-1.3.1+wv0.12.0-nightly.1.jar",
          "size": 261,
          "sha512": "d40d091aec95beef7eac4f47de90ab91a989b656a94c065d097ceb4b94507f2fc4709d838af6f071727217190c07e1fb4efaaaceb4e8ed0ae2057c997034be4f",
          "sha256": "574a561acafd9685a92f10bb7fcce336fdd28c5d01889490b8217185af83260e",
          "sha1": "e37be2cab5bd0f412c17e6d36d94532a2708e85b",
          "md5": "41c9a47ed490bdb0115160a415bcf651"
        }
      ]
    }
  ]
}
