{
  "formatVersion": "1.1",
  "component": {
    "group": "net.notjustanna.webview",
    "module": "webview_java-interop-gson",
    "version": "1.3.0+wv0.12.0-nightly.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.notjustanna.webview",
          "module": "webview_java-interop",
          "version": {
            "requires": "1.3.0+wv0.12.0-nightly.1"
          }
        }
      ],
      "files": [
        {
          "name": "webview_java-interop-gson-1.3.0+wv0.12.0-nightly.1.jar",
          "url": "webview_java-interop-gson-1.3.0+wv0.12.0-nightly.1.jar",
          "size": 3290,
          "sha512": "61b73546b36631b47d82608748b3092df64d6584fe744ec5398cbdb8de806c3622a30c197125279e332ce850135fcc28a5c15af10671a760d8a6f8b180e8f9d1",
          "sha256": "60f2ba851aa9cade43c158aa1b25762d90cfa85ab6224116751e4c3e1a98f19a",
          "sha1": "125dfbcd771181c3c2cdf03115c78389416c795e",
          "md5": "019d60ec6a2441462ed1502c34652783"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.notjustanna.webview",
          "module": "webview_java",
          "version": {
            "requires": "1.3.0+wv0.12.0-nightly.1"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.17.0"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.17.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.12.1"
          }
        },
        {
          "group": "net.notjustanna.webview",
          "module": "webview_java-interop",
          "version": {
            "requires": "1.3.0+wv0.12.0-nightly.1"
          }
        }
      ],
      "files": [
        {
          "name": "webview_java-interop-gson-1.3.0+wv0.12.0-nightly.1.jar",
          "url": "webview_java-interop-gson-1.3.0+wv0.12.0-nightly.1.jar",
          "size": 3290,
          "sha512": "61b73546b36631b47d82608748b3092df64d6584fe744ec5398cbdb8de806c3622a30c197125279e332ce850135fcc28a5c15af10671a760d8a6f8b180e8f9d1",
          "sha256": "60f2ba851aa9cade43c158aa1b25762d90cfa85ab6224116751e4c3e1a98f19a",
          "sha1": "125dfbcd771181c3c2cdf03115c78389416c795e",
          "md5": "019d60ec6a2441462ed1502c34652783"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webview_java-interop-gson-1.3.0+wv0.12.0-nightly.1-sources.jar",
          "url": "webview_java-interop-gson-1.3.0+wv0.12.0-nightly.1-sources.jar",
          "size": 2909,
          "sha512": "3c4d7deb568caa50c4b3d37fbb730f5418643f8b1fc45cd2734f144a8df1db58773c4f1f315b0b88f855debbe895b11455b569adbe0d53f97f697ff1c97a98f3",
          "sha256": "986729366489a2bfa95c78234757d61f7608fcb3e1b3a10a20b33935a4f3fe16",
          "sha1": "8906095b5fa28302508a95f7586f897b95841b42",
          "md5": "b4aaed8c1157ce0ef77184e0b78fd2cc"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webview_java-interop-gson-1.3.0+wv0.12.0-nightly.1-javadoc.jar",
          "url": "webview_java-interop-gson-1.3.0+wv0.12.0-nightly.1-javadoc.jar",
          "size": 89755,
          "sha512": "9e0849e18da0b5d9427ad520f90ff2b0cb0b3737fac8903263c6adb1e421d218900411740776696b7cbdca232134e52498494bf06ab8bfad8be71b620923203a",
          "sha256": "14a6caeb469730c8a272d64de567aba4f45b96091caf9bb944ed0269b922dbe5",
          "sha1": "5514f6b22db59bf9d50c2e596c50b79c680edda5",
          "md5": "8ac2ab484824c3059b24c90bce14d482"
        }
      ]
    }
  ]
}
