{
  "formatVersion": "1.1",
  "component": {
    "group": "net.notjustanna.webview",
    "module": "webview_java-native-linux-x86-64",
    "version": "1.3.0+wv0.12.0-nightly.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "webview_java-native-linux-x86-64-1.3.0+wv0.12.0-nightly.1.jar",
          "url": "webview_java-native-linux-x86-64-1.3.0+wv0.12.0-nightly.1.jar",
          "size": 40776,
          "sha512": "440a98ae569d56d6a79edd013a3d934f5a1a5c2de06cd40cbb7417237b30a69bdb657d22ba9f77a39c1bd7336c14db0af2a28c2d902fdfa09366a9572c8d0a1d",
          "sha256": "7527165b0ed9d93fc3a842263de4d230e977df3a343fc42fefb44e1e6b636ca6",
          "sha1": "1374ad0e986887c8885ab9521a2a2d55abd5dbec",
          "md5": "89a8029a3fad2160353e3dee79040b8b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webview_java-native-linux-x86-64-1.3.0+wv0.12.0-nightly.1.jar",
          "url": "webview_java-native-linux-x86-64-1.3.0+wv0.12.0-nightly.1.jar",
          "size": 40776,
          "sha512": "440a98ae569d56d6a79edd013a3d934f5a1a5c2de06cd40cbb7417237b30a69bdb657d22ba9f77a39c1bd7336c14db0af2a28c2d902fdfa09366a9572c8d0a1d",
          "sha256": "7527165b0ed9d93fc3a842263de4d230e977df3a343fc42fefb44e1e6b636ca6",
          "sha1": "1374ad0e986887c8885ab9521a2a2d55abd5dbec",
          "md5": "89a8029a3fad2160353e3dee79040b8b"
        }
      ]
    }
  ]
}
