{
  "formatVersion": "1.1",
  "component": {
    "group": "net.notjustanna.webview",
    "module": "webview_java-interop",
    "version": "1.3.0+wv0.12.0-nightly.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "webview_java-interop-1.3.0+wv0.12.0-nightly.1.jar",
          "url": "webview_java-interop-1.3.0+wv0.12.0-nightly.1.jar",
          "size": 6093,
          "sha512": "1f4a63b305f3cbc8f7a71c937296dc611aa37458fe3e81dddc4eb0418a28900eccf9ed80ca5c96adde18122b631d3dc10bc6a2fc7945019ce73c9d0e28989c17",
          "sha256": "d4c54fda3c7cdc6f5a8bb81139fde4f7b4df1ebb07faeef1a073292d3335bb73",
          "sha1": "78a89b7683716186c989145671eda478ee43ef56",
          "md5": "e719486edadc40c01f81f2a4836e1fc5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.notjustanna.webview",
          "module": "webview_java",
          "version": {
            "requires": "1.3.0+wv0.12.0-nightly.1"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.17.0"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.17.0"
          }
        }
      ],
      "files": [
        {
          "name": "webview_java-interop-1.3.0+wv0.12.0-nightly.1.jar",
          "url": "webview_java-interop-1.3.0+wv0.12.0-nightly.1.jar",
          "size": 6093,
          "sha512": "1f4a63b305f3cbc8f7a71c937296dc611aa37458fe3e81dddc4eb0418a28900eccf9ed80ca5c96adde18122b631d3dc10bc6a2fc7945019ce73c9d0e28989c17",
          "sha256": "d4c54fda3c7cdc6f5a8bb81139fde4f7b4df1ebb07faeef1a073292d3335bb73",
          "sha1": "78a89b7683716186c989145671eda478ee43ef56",
          "md5": "e719486edadc40c01f81f2a4836e1fc5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webview_java-interop-1.3.0+wv0.12.0-nightly.1-sources.jar",
          "url": "webview_java-interop-1.3.0+wv0.12.0-nightly.1-sources.jar",
          "size": 4637,
          "sha512": "11cea7e62da76712c979e6d93048eaed27da93157417370336d41acd649699f6be2e403504a2b107c12c2902bf3907e71e54cb70f8e0ed0afee87fd282f7ccad",
          "sha256": "47cc793ac65bf4faafa3b4ee15c44576177f264153f2fbecd89c0e5d4d9040d4",
          "sha1": "2ffc2846efdd0631f1f28d5bc9af2a33c8308a74",
          "md5": "94b14089bf7dd2b80f5ba8c3b77b26ab"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webview_java-interop-1.3.0+wv0.12.0-nightly.1-javadoc.jar",
          "url": "webview_java-interop-1.3.0+wv0.12.0-nightly.1-javadoc.jar",
          "size": 94138,
          "sha512": "735bdd25a4421411ad211c073d54985bfdb2d6ce5f0d183ef59585ba1df326ebb9706fa0df2d57c80e578179b035f9464272e04f09a2a8b0674c321deafa24e3",
          "sha256": "6829c4c91093f4c0ab3b806f9a5ab9d19f81def5aa1f8b269e3e8844d5ee6cf5",
          "sha1": "e810faf684dae335698629f765713fe3b9df7378",
          "md5": "1477a1bf14caf052f34202ab2c8e6206"
        }
      ]
    }
  ]
}
