{
  "formatVersion": "1.1",
  "component": {
    "group": "net.notjustanna.webview",
    "module": "webview_java-native-windows-x86-64",
    "version": "1.1.1+wv0.12.0-nightly.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "webview_java-native-windows-x86-64-1.1.1+wv0.12.0-nightly.1.jar",
          "url": "webview_java-native-windows-x86-64-1.1.1+wv0.12.0-nightly.1.jar",
          "size": 46811,
          "sha512": "5ae11d3143dca48d6316144ad6a2cd5f9d54abe72c68ee0c7423ae5be88f0e642a58863f55aef5cadb82842c7cb80c9f17ce91ad1757077e793d6222f9963476",
          "sha256": "159f967032c22e3bbcd72f1ef9e4a28c661f0b676c5c77e6170fd8559b55fe92",
          "sha1": "6ff8950a1641365795222454560612d5f7612295",
          "md5": "d365e199ed0c724a4741cc914506ea71"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webview_java-native-windows-x86-64-1.1.1+wv0.12.0-nightly.1.jar",
          "url": "webview_java-native-windows-x86-64-1.1.1+wv0.12.0-nightly.1.jar",
          "size": 46811,
          "sha512": "5ae11d3143dca48d6316144ad6a2cd5f9d54abe72c68ee0c7423ae5be88f0e642a58863f55aef5cadb82842c7cb80c9f17ce91ad1757077e793d6222f9963476",
          "sha256": "159f967032c22e3bbcd72f1ef9e4a28c661f0b676c5c77e6170fd8559b55fe92",
          "sha1": "6ff8950a1641365795222454560612d5f7612295",
          "md5": "d365e199ed0c724a4741cc914506ea71"
        }
      ]
    }
  ]
}
