{
  "formatVersion": "1.1",
  "component": {
    "group": "net.notjustanna.webview",
    "module": "webview_java-all-natives",
    "version": "1.3.0+wv0.12.0-nightly.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "webview_java-all-natives-1.3.0+wv0.12.0-nightly.1.jar",
          "url": "webview_java-all-natives-1.3.0+wv0.12.0-nightly.1.jar",
          "size": 261,
          "sha512": "fd69a5e5750855729c6a90281a7c72856c22321a1c6d5b2db22a95ebb2898b4e34dcdb642b2b1232be83c20827eccdbff27fb3f14e82e6d004e0a32086d901e7",
          "sha256": "11b35681f0da975fba0be21072dfc69a71cb61e359d8a4757f4b3a149f456a1f",
          "sha1": "870ed5fefb31f818ca476783e30b8ee96049c670",
          "md5": "f1ae64c5347e1c0a75458bef38e4b329"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.notjustanna.webview",
          "module": "webview_java-native-darwin",
          "version": {
            "requires": "1.3.0+wv0.12.0-nightly.1"
          }
        },
        {
          "group": "net.notjustanna.webview",
          "module": "webview_java-native-linux-x86-64",
          "version": {
            "requires": "1.3.0+wv0.12.0-nightly.1"
          }
        },
        {
          "group": "net.notjustanna.webview",
          "module": "webview_java-native-windows-arm64",
          "version": {
            "requires": "1.3.0+wv0.12.0-nightly.1"
          }
        },
        {
          "group": "net.notjustanna.webview",
          "module": "webview_java-native-windows-x86",
          "version": {
            "requires": "1.3.0+wv0.12.0-nightly.1"
          }
        },
        {
          "group": "net.notjustanna.webview",
          "module": "webview_java-native-windows-x86-64",
          "version": {
            "requires": "1.3.0+wv0.12.0-nightly.1"
          }
        }
      ],
      "files": [
        {
          "name": "webview_java-all-natives-1.3.0+wv0.12.0-nightly.1.jar",
          "url": "webview_java-all-natives-1.3.0+wv0.12.0-nightly.1.jar",
          "size": 261,
          "sha512": "fd69a5e5750855729c6a90281a7c72856c22321a1c6d5b2db22a95ebb2898b4e34dcdb642b2b1232be83c20827eccdbff27fb3f14e82e6d004e0a32086d901e7",
          "sha256": "11b35681f0da975fba0be21072dfc69a71cb61e359d8a4757f4b3a149f456a1f",
          "sha1": "870ed5fefb31f818ca476783e30b8ee96049c670",
          "md5": "f1ae64c5347e1c0a75458bef38e4b329"
        }
      ]
    }
  ]
}
