name: Gradle Package

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Build with Gradle
        run: ./gradlew build

      - name: Checkout maven
        uses: actions/checkout@v4
        with:
          ref: maven
          path: .repo

      - name: Publish to Maven Local
        run: ./gradlew publishAllPublicationsToLocalRepository

      - name: Update README
        uses: actions/github-script@v7
        with:
          script: |
            const it = require("./.github/workflows/write-readme.js");
            await it.main("./.repo/README.md");

      - name: Commit and push
        uses: actions-js/push@master
        with:
          directory: .repo
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: maven
          rebase: true
